site_name: Siddhi GPL Execution Geo
site_description: Siddhi GPL Execution Geo Extension
site_author: WSO2
site_url: https://wso2-extensions.github.io/siddhi-gpl-execution-geo/
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
repo_name: Siddhi-GPL-Execution-Geo
repo_url: https://github.com/wso2-extensions/siddhi-gpl-execution-geo
copyright: Copyright &copy; 2011 - 2018 WSO2
theme:
  name: material
  logo: images/siddhi-logo-w.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
extra:
  social:
  - type: github
    link: https://github.com/wso2/siddhi
  - type: linkedin
    link: https://www.linkedin.com/groups/13553064
pages:
- Welcome: index.md
- API Docs:
  - 5.0.0: api/5.0.0.md
  - 4.0.18: api/4.0.18.md
  - 4.0.17: api/4.0.17.md
  - 4.0.16: api/4.0.16.md
  - 4.0.15: api/4.0.15.md
  - 4.0.14: api/4.0.14.md
  - 4.0.13: api/4.0.13.md
  - 4.0.12: api/4.0.12.md
  - 4.0.11: api/4.0.11.md
  - 4.0.10: api/4.0.10.md
  - 4.0.9: api/4.0.9.md
  - 4.0.8: api/4.0.8.md
  - 4.0.7: api/4.0.7.md
  - 4.0.6: api/4.0.6.md
  - 4.0.5: api/4.0.5.md
  - 4.0.4: api/4.0.4.md
  - latest: api/latest.md
- License: license.md
